//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.02 at 09:28:25 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ps.com/tutorial/model/country", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ps.tutorial.model.country;
